apiVersion: batch/v1
kind: Job
metadata:
  name: "{{.Release.Name}}-joinchannel"
  labels:
    app: "join-channel"
    chart: "join-channel-job"
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/managed-by: {{.Release.Service | quote }}
    app.kubernetes.io/instance: {{.Release.Name | quote }}
    helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
  annotations:
    "helm.sh/hook": "post-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": hook-succeeded
spec:
  template:
    metadata:
      name: "{{.Release.Name}}"
      labels:
        app: "join-channel"
        release: {{ .Release.Name }}
        heritage: {{ .Release.Service }}
        app.kubernetes.io/managed-by: {{.Release.Service | quote }}
        app.kubernetes.io/instance: {{.Release.Name | quote }}
        helm.sh/chart: "{{.Chart.Name}}-{{.Chart.Version}}"
    spec:
      restartPolicy: Never
      containers:
      - name: join-channel
        image: "{{ .Values.peerimage.repository }}:{{ .Values.peerimage.tag }}"
        command: ["sh", "-c"," sleep 30; peer channel fetch config -o
          {{- if .Values.global.orderer.deployorderer }} {{ .Values.global.org.name }}-{{ .Values.global.orderer.name }}:{{ .Values.global.orderer.port }}
          {{- else }} {{ .Values.global.orderer.ip }}:{{ .Values.global.orderer.externalport }}
          {{- end }} -c {{ .Values.global.channelname }} && peer channel join -b {{ .Values.global.channelname }}_config.block"]
        envFrom:
          - configMapRef:
              name: channels-config
        volumeMounts:
        - name: join-channel-config
          mountPath: /fabric-config/
      volumes:
      - name: join-channel-config
        secret:
          secretName: join-channel-config
          items:
{{- include "secret.users.index" . | indent 10}}

