{{ if .Values.global.orderer.deployorderer }}
apiVersion: v1
kind: Secret
metadata:
  name: create-channel-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := (printf "environment/crypto-config/peerOrganizations/%s/peers/peer0.%s/**" .Values.global.org.name .Values.global.org.name) }}
{{- $networkfile := printf "environment/%s" .Values.global.networkfilename }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{ .Values.global.networkfilename | indent 2 }}: {{ (.Files.Get $networkfile) | b64enc}}
{{end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: join-channel-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/users/admin-%s/**" .Values.global.org.name .Values.global.org.name }}
{{- $networkfile := printf "environment/%s" .Values.global.networkfilename }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{ .Values.global.networkfilename  | indent 2 }}: {{ (.Files.Get $networkfile)  | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-bna-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/users/admin-%s/**" .Values.global.org.name .Values.global.org.name }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
  {{ .Values.global.bnafile }}: {{ (.Files.Get "environment/digital-cmr-network.bna") | b64enc}}
