---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: peer0-kpm-all-pv
    labels:
      vol: peer0-kpm-all-pv
spec:
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/var/peer0-kpm-all"
---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: bc-peer0-kpm-all-couchdb-pv
    labels:
      vol: bc-peer0-kpm-all-couchdb-pv
spec:
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/var/peer0-kpm-all-couchdb"
