---
apiVersion: v1
kind: Pod
metadata:
  name: utils
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-credentials
    hostPath:
      path: /composer
  containers:
  - name: bootstrap
    image: ibmblockchain/fabric-tools:1.0.6
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep 1 && mkdir -p /home/composer && chown 100 /home/composer && echo 'Done with bootstrapping'" ]
    volumeMounts:
    - mountPath: /home
      name: composer-credentials
---
apiVersion: v1
kind: Pod
metadata:
  name: composer-identity-import-kpm-pon
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-credentials
    hostPath:
      path: /composer
  - name: composer-identity-fabric-config
    emptyDir: {}
  containers:
  - name: composer-identity-import-kpm-pon
    image: hyperledger/composer-cli:0.13.2
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep 1 && while [ ! -d /fabric-config/Admin@kpm-pon ]; do echo Waiting for identity dataa; sleep 1; done; composer identity import -p hlfv1 -u PeerAdmin -c /fabric-config/Admin@kpm-pon/msp/signcerts/Admin@kpm-pon-cert.pem -k /fabric-config/Admin@kpm-pon/msp/keystore/5f33a8da3b835489fe5838aee615f52663e187b308ef908686fc60bdd9b73242_sk && echo 'Done with importing identity'"]
    env:
    - name: COMPOSER_CONFIG
      value: >
        {
          "defaultConnectionProfile": "hlfv1",
          "connectionProfiles": {
            "hlfv1": {
              "type": "hlfv1",
              "orderers": [
                  {
                      "url": "grpc://orderer-kpm-pon:31010"
                  }
              ],
              "ca": {
                  "url": "http://ca-kpm-pon:7054",
                  "name": "ca-kpm-pon"
              },
              "peers": [
                  {
                      "requestURL": "grpc://peer0-kpm-pon:5010",
                      "eventURL": "grpc://peer0-kpm-pon:5011"
                  }
              ],
              "keyValStore": "/home/composer/.hfc-key-store",
              "channel": "composerchannel",
              "mspID": "kpm-ponMSP",
              "timeout": "300"
            }
          },
          "credentials": {
            "hlfv1": {
              "PeerAdmin": "notneeded",
              "admin": "adminpw"
            }
          }
        }
    volumeMounts:
    - name: composer-credentials
      mountPath: /home
    - name: composer-identity-fabric-config
      mountPath: /fabric-config
      