kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.global.peer.couchdb.name }}-pvc
  labels:
    app: {{ .Values.global.peer.couchdb.name }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      vol: peer0-couchdb-pv