apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.org.name }}-{{ .Values.global.peer.couchdb.name }}
  labels:
    app: {{ .Values.global.org.name }}-{{ .Values.global.peer.couchdb.name }}
    chart: {{ template "blockchain-peer-couchdb.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.global.peer.couchdb.port }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Values.global.org.name }}-{{ .Values.global.peer.couchdb.name }}
    release: {{ .Release.Name }}
