---
apiVersion: v1
kind: Pod
metadata:
  name: wipeshared
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-credentials
    hostPath:
      path: /composer
  - name: shared
    hostPath:
      path: /tmp
  - name: org1peer1-pv
    hostPath:
      path: /var/org1peer1
  - name: org2peer1-pv
    hostPath:
      path: /var/org2peer1
  - name: bc-couchdb1-pv
    hostPath:
      path: /var/couchdb1
  - name: bc-couchdb2-pv
    hostPath:
      path: /var/couchdb2
  - name: credentials-pv
    hostPath:
      path: /var/.composer-credentials
  - name: privatedb-pv
    hostPath:
      path: /var/privatedb

  containers:
  - name: wipeshared
    image: ibmblockchain/fabric-tools:1.0.6
    imagePullPolicy: Always
    command: ["sh", "-c", "rm -rf /shared/* /home/* /org1peer1/* /org2peer1/* /couchdb1/* /couchdb2/* /.composer-credentials/* /privatedb/*"]
    volumeMounts:
    - name: composer-credentials
      mountPath: /home
    - name: shared
      mountPath: /shared
    - name: org1peer1-pv
      mountPath: /org1peer1
    - name: org2peer1-pv
      mountPath: /org2peer1
    - name: bc-couchdb1-pv
      mountPath: /couchdb1
    - name: bc-couchdb2-pv
      mountPath: /couchdb2
    - name: credentials-pv
      mountPath: /.composer-credentials
    - name: privatedb-pv
      mountPath: /privatedb