---
apiVersion: v1
kind: Service
metadata:
  name: privatedb-all
  labels:
    app: privatedb-all
    tier: db
spec:
  type: NodePort
  selector:
    tier: db
  ports:
  - protocol: TCP
    port: 5984
    nodePort: 31003
    name: http