---
apiVersion: v1
kind: Pod
metadata:
  name: couchdb-private
  labels:
    name: couchdb-private
spec:
  restartPolicy: "Always"
  containers:
  - name: couchdb-private
    image: couchdb:1.7.0
    imagePullPolicy: Always

---
apiVersion: v1
kind: Pod
metadata:
  name: app-server
  labels:
    name: app-server
spec:
  restartPolicy: "Always"
  containers:
  - name: app-server
    image: registry.eu-gb.bluemix.net/koopman/digitalcmr_server
    imagePullPolicy: Always
    imagePullSecrets:
    - name: bluemix-uk-registry
    command: ["sh", "-c", "sleep 30 && npm start"]
    env:
    - name: NODE_ENV
      value: production
    - name: HOST
      value: "0.0.0.0"
    - name: PORT
      value: "8080"

---
apiVersion: v1
kind: Pod
metadata:
  name: app-client
  labels:
    name: app-client
spec:
  restartPolicy: "Always"
  containers:
  - name: app-client
    image: registry.eu-gb.bluemix.net/koopman/digitalcmr_client
    imagePullPolicy: Always
    imagePullSecrets:
    - name: bluemix-uk-registry
    command: ["sh", "-c", "./node_modules/.bin/ng serve -H 0.0.0.0 -e prod --disable-host-check"]

---
apiVersion: v1
kind: Pod
metadata:
  name: api-doc
  labels:
    name: api-doc
spec:
  restartPolicy: "Always"
  containers:
  - name: api-doc
    image: registry.eu-gb.bluemix.net/koopman/digitalcmr_api_doc
    imagePullPolicy: Always
    imagePullSecrets:
    - name: bluemix-uk-registry
