version: '2.0'
services:
  server:
    build:
      context: server
    ports:
      - 8080:8080
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
      - ./server/package.json:/usr/src/app/package.json
      - ./server/resources/connectionProfiles:/root/.composer-connection-profiles
      - ./server/resources:/usr/src/app/resources
    depends_on:
      - private-db
    command: sh -c "npm start"

  client:
      build: client
      ports:
          - "4200:4200"
          - "49153:49153"
      volumes:
          - ./client/src:/usr/src/app/src
          - ./client/.angular-cli.json:/usr/src/app/.angular-cli.json
          - ./client/tslint.json:/usr/src/app/tslint.json
      command: sh -c "node_modules/.bin/ng lint && node_modules/.bin/ng serve --host 0.0.0.0"

  private-db:
    container_name: private-db
    image: couchdb:1.7.0
    ports:
      - "5985:5984"

  api:
    container_name: api
    build: api_doc
    volumes:
      - ./api_doc:/docs/
    ports:
      - "8001:8080"
    environment:
      - SWAGGER_JSON=/docs/all.api.json