version: '2.0'
services:
  server:
    build:
      context: server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=local
      - INIT=true
      - TLS=false
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json
      - ./server/package.json:/usr/src/app/package.json
      - ./server/resources/connectionProfiles:/root/.composer-connection-profiles
      - ./server/resources:/usr/src/app/resources
    depends_on:
      - privatedb
    command: sh -c "npm start"

  privatedb:
    container_name: privatedb
    image: couchdb:2.1.1
    ports:
      - "5985:5984"

  api_doc:
    container_name: api_doc
    build: api_doc
    volumes:
      - ./api_doc:/docs/
    ports:
      - "8001:8080"
    environment:
      - SWAGGER_JSON=/docs/all.api.json