version: '2.0'
services:
  server:
    build:
      context: server
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    ports:
      - 8080:8080
    env_file: ./server/.env
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
      - ./server/package.json:/usr/src/app/package.json
      - ./server/resources/connectionProfiles:/root/.composer-connection-profiles
      - ./server/resources/testData.json:/usr/src/app/resources/testData.json
    command: bash -c "grunt build; grunt"

  client:
      build: client
      ports:
          - "4200:4200"
          - "49153:49153"
      volumes:
          - ./client/src:/usr/src/app/src
          - ./client/.angular-cli.json:/usr/src/app/.angular-cli.json
          - ./client/tslint.json:/usr/src/app/tslint.json
      command: bash -c "ng lint && ng serve --host 0.0.0.0"

  couchdb-private:
    container_name: couchdb-private
    image: couchdb
    ports:
      - "5985:5984"