version: '2.1'
services:
  ca0:
    image: hyperledger/fabric-ca:x86_64-1.0.0-alpha
    environment:
      - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
    ports:
      - 7054:7054
    command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/peerOrg1-cert.pem --ca.keyfile /etc/hyperledger/fabric-ca-server-config/d8a5b3cac1b821f6e4b487ceaf1fd239cdcfc310894150908b90f05e9179556a_sk -b admin:adminpw' -d
    volumes:
      - ./composer/hlfv1/crypto-config/peerOrganizations/peerOrg1/ca/:/etc/hyperledger/fabric-ca-server-config
    container_name: ca_peerOrg1

  orderer0:
    container_name: orderer0
    extends:
      file: compose-defaults.yml
      service: orderer

  peer0:
    container_name: peer0
    extends:
      file: compose-defaults.yml
      service: peer
    environment:
  #      - CORE_LOGGING_LEVEL=DEBUG
      - CORE_PEER_ID=peer0
      - CORE_PEER_GOSSIP_ORGLEADER=true
      - CORE_PEER_ADDRESS=peer0:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0:7051
    command: peer node start --peer-defaultchain=false
    ports:
      - 7051:7051
      - 7053:7053
    volumes:
        - ./composer/hlfv1/crypto-config/peerOrganizations/peerOrg1/peers/peerOrg1Peer1/:/etc/hyperledger/msp/peer
#        - ./tls/peers/peer0:/etc/hyperledger/tls
    depends_on:
      - orderer0

  peer1:
    container_name: peer1
    extends:
      file: compose-defaults.yml
      service: peer
    environment:
      - CORE_PEER_ID=peer1
      - CORE_PEER_GOSSIP_ORGLEADER=false
      - CORE_PEER_ADDRESS=peer1:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1:7051
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    ports:
      - 7056:7051
      - 7058:7053
    volumes:
        - ./composer/hlfv1/crypto-config/peerOrganizations/peerOrg1/peers/peerOrg1Peer2/:/etc/hyperledger/msp/peer
#        - ./composer/hlfv1/tls/peers/peer1:/etc/hyperledger/tls
    depends_on:
      - orderer0
      - peer0

  composer:
    build: composer
    ports:
      - 3000:3000
    volumes:
      - ./composer/bna:/bna
    depends_on:
      - orderer0
      - peer0
      - peer1
      - ca0
    env_file: ./composer/.env

  server:
    build:
      context: server
      args:
        NPM_TOKEN: ${NPM_TOKEN}
    ports:
      - 8080:8080
    env_file: ./server/.env
    environment:
      - NPM_TOKEN=${NPM_TOKEN}
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
      - ./server/package.json:/usr/src/app/package.json
    links:
      - composer
    command: bash -c "grunt"
