version: '2.0'
services:

  client:
      build: client
      ports:
          - "4200:4200"
          - "49153:49153"
      volumes:
          - ./client/src:/usr/src/app/src
          - ./client/.angular-cli.json:/usr/src/app/.angular-cli.json
          - ./client/tslint.json:/usr/src/app/tslint.json
      command: bash -c "ng lint && ng serve --host 0.0.0.0"

# docker-compose -f docker-client-only.yml up --force-recreate