version: '2.0'
services:
  server-kpm-pon:
    container_name: server-kpm-pon
    build:
      context: server
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=kpm-pon
      - INIT=true
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
      - ./server/package.json:/usr/src/app/package.json
      - ./server/resources/connectionProfiles:/root/.composer-connection-profiles
      - ./server/resources:/usr/src/app/resources
    depends_on:
      - privatedb-kpm-pon
    command: sh -c "npm start"

  client-kpm-pon:
      container_name: client-kpm-pon
      build: client
      ports:
          - "4200:4200"
          - "49153:49153"
      volumes:
          - ./client/src:/usr/src/app/src
          - ./client/.angular-cli.json:/usr/src/app/.angular-cli.json
          - ./client/tslint.json:/usr/src/app/tslint.json
      command: sh -c "node_modules/.bin/ng lint && node_modules/.bin/ng serve --host 0.0.0.0 -e kpmpon"

  privatedb-kpm-pon:
    container_name: privatedb-kpm-pon
    image: couchdb:2.1.1
    ports:
      - "5994:5984"

  server-pon:
    container_name: server-pon
    build:
      context: server
    ports:
      - "8081:8080"
    environment:
      - NODE_ENV=pon
      - HOST=0.0.0.0
      - PORT=8080
    volumes:
      - ./server/src:/usr/src/app/src
      - ./server/tsconfig.json:/usr/src/app/tsconfig.json # TS filenames get added automatically to this file on build
      - ./server/package.json:/usr/src/app/package.json
      - ./server/resources/connectionProfiles:/root/.composer-connection-profiles
      - ./server/resources:/usr/src/app/resources
    depends_on:
      - privatedb-pon
    command: sh -c "npm start"

  client-pon:
      container_name: client-pon
      build: client
      ports:
          - "4201:4200"
          - "49154:49153"
      volumes:
          - ./client/src:/usr/src/app/src
          - ./client/.angular-cli.json:/usr/src/app/.angular-cli.json
          - ./client/tslint.json:/usr/src/app/tslint.json
      command: sh -c "node_modules/.bin/ng lint && node_modules/.bin/ng serve --host 0.0.0.0 -e pon"

  privatedb-pon:
    container_name: privatedb-pon
    image: couchdb:2.1.1
    ports:
      - "5995:5984"