---
apiVersion: v1
kind: Service
metadata:
  name: persistent-couchdb-private
  labels:
    app: persistent-couchdb-private
    tier: db
spec:
  type: NodePort
  selector:
    tier: db
  ports:
  - protocol: TCP
    port: 5984
    nodePort: 31003
    name: http