---
# The service to expose composer playground
apiVersion: v1
kind: Service
metadata:
  name: composer-playground-all
  labels:
    run: composer-playground-all
spec:
  type: NodePort
  selector:
    name: composer-playground-all
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31080
    name: http