export enum Transaction {
  CreateEcmrs                          = 'CreateECMRs',
  UpdateEcmrStatusToLoaded             = 'UpdateEcmrStatusToLoaded',
  UpdateEcmrStatusToInTransit          = 'UpdateEcmrStatusToInTransit',
  UpdateEcmrStatusToDelivered          = 'UpdateEcmrStatusToDelivered',
  UpdateEcmrStatusToConfirmedDelivered = 'UpdateEcmrStatusToConfirmedDelivered',
  UpdateEcmrStatusToCancelled          = 'UpdateECMRStatusToCancelled',
  UpdateExpectedDeliveryWindow         = 'UpdateExpectedDeliveryWindow',
  UpdateExpectedPickupWindow           = 'UpdateExpectedPickupWindow',
  CreateTransportOrders                = 'CreateTransportOrders',
  CreateTransportOrder                 = 'CreateTransportOrder',
  UpdateTransportOrder                 = 'UpdateTransportOrder',
  UpdateTransportOrderPickupWindow     = 'UpdateTransportOrderPickupWindow',
  UpdateTransportOrderDeliveryWindow   = 'UpdateTransportOrderDeliveryWindow',
  UpdateTransportOrderStatusToCancelled = 'UpdateTransportOrderStatusToCancelled',
  CreateVehicles                        = 'CreateVehicles',
  CreateCarrierOrg                      = 'CreateCarrierOrg',
  CreateCompoundOrg                     = 'CreateCompoundOrg',
  CreateLegalOwnerOrg                   = 'CreateLegalOwnerOrg',
  CreateRecipientOrg                    = 'CreateRecipientOrg'
}