export enum Transaction {
  CreateEcmrs                           = 'CreateECMRs',
  CreateEcmr                            = 'CreateECMR',
  UpdateEcmr                            = 'UpdateECMR',
  UpdateEcmrStatusToCancelled           = 'UpdateECMRStatusToCancelled',
  UpdateExpectedDeliveryWindow          = 'UpdateExpectedDeliveryWindow',
  UpdateExpectedPickupWindow            = 'UpdateExpectedPickupWindow',
  CreateTransportOrders                 = 'CreateTransportOrders',
  CreateTransportOrder                  = 'CreateTransportOrder',
  UpdateTransportOrder                  = 'UpdateTransportOrder',
  UpdateTransportOrderPickupWindow      = 'UpdateTransportOrderPickupWindow',
  UpdateTransportOrderDeliveryWindow    = 'UpdateTransportOrderDeliveryWindow',
  UpdateTransportOrderStatusToCancelled = 'UpdateTransportOrderStatusToCancelled',
  CreateVehicles                        = 'CreateVehicles',
  CreateVehicle                         = 'CreateVehicle',
  CreateCarrierOrg                      = 'CreateCarrierOrg',
  CreateCompoundOrg                     = 'CreateCompoundOrg',
  CreateLegalOwnerOrg                   = 'CreateLegalOwnerOrg',
  CreateRecipientOrg                    = 'CreateRecipientOrg'
}