---
apiVersion: v1
kind: Pod
metadata:
  name: wipeshared
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-credentials
    hostPath:
      path: /composer

  containers:
  - name: wipeshared
    image: ibmblockchain/fabric-tools:1.0.6
    imagePullPolicy: Always
    command: ["sh", "-c", "rm -rf /home/*"]
    volumeMounts:
    - name: composer-credentials
      mountPath: /home