apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.org.name }}-{{ .Values.global.peer.name }}-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  CORE_PEER_ADDRESSAUTODETECT: "true"
  CORE_PEER_NETWORKID: nid1
  CORE_PEER_ADDRESS: "127.0.0.1:{{ .Values.global.peer.requestport }}"
  CORE_PEER_LISTENADDRESS: "0.0.0.0:{{ .Values.global.peer.requestport }}"
  CORE_PEER_EVENTS_ADDRESS: "0.0.0.0:{{ .Values.global.peer.eventport }}"
  CORE_PEER_GOSSIP_BOOTSTRAP: "127.0.0.1:{{ .Values.global.peer.requestport }}"
  CORE_PEER_GOSSIP_ORGLEADER: "true"
  CORE_PEER_GOSSIP_SKIPHANDSHAKE: "true"
  CORE_PEER_COMMITTER_ENABLED: "true"
  CORE_PEER_PROFILE_ENABLED: "true"
  CORE_PEER_DISCOVERY_PERIOD: 60s
  CORE_PEER_DISCOVERY_TOUCHPERIOD: 60s
  CORE_VM_ENDPOINT: "unix:///host/var/run/docker.sock"
  CORE_PEER_LOCALMSPID: {{ .Values.global.org.name}}MSP
  CORE_PEER_MSPCONFIGPATH: /fabric-config/msp
  CORE_LOGGING_LEVEL: {{ .Values.global.loglevel }}
  CORE_LOGGING_PEER: {{ .Values.global.loglevel }}
  CORE_LOGGING_CAUTHDSL: {{ .Values.global.loglevel }}
  CORE_LOGGING_GOSSIP: {{ .Values.global.loglevel }}
  CORE_LOGGING_LEDGER: {{ .Values.global.loglevel }}
  CORE_LOGGING_MSP: info
  CORE_LOGGING_POLICIES: {{ .Values.global.loglevel }}
  CORE_LOGGING_GRPC: {{ .Values.global.loglevel }}
  CORE_PEER_TLS_ENABLED: "false"
  CORE_LEDGER_STATE_STATEDATABASE: CouchDB # : goleveldb
  CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS: "{{ .Values.global.org.name }}-{{ .Values.global.peer.couchdb.name }}:{{ .Values.global.peer.couchdb.port }}"
  PEER_CFG_PATH: peer_config/
  FABRIC_CFG_PATH: /etc/hyperledger/fabric/
  {{- if .Values.global.orderer.deployorderer }}
  ORDERER_URL: "{{.Values.global.org.name}}-{{ .Values.global.org.name }}-{{ .Values.global.orderer.name }}:{{ .Values.global.orderer.port }}"
  {{- else }}
  ORDERER_URL: "{{ .Values.global.orderer.ip }}:{{ .Values.global.orderer.externalport }}"
  {{- end }}
  GODEBUG: "netdns=go"