apiVersion: v1
kind: Secret
metadata:
  name: msp-config-{{ .Values.global.peer.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  admin-org1-cert.pem: {{ (.Files.Get "certs/msp/admincerts/admin-org1-cert.pem") | b64enc}}
  ca.org1-cert.pem: {{ (.Files.Get "certs/msp/cacerts/ca.org1-cert.pem") | b64enc}}
  ae2cbdd5ed5a1960096ff0430d981bc86a91f7a09b84acbe6261602039b04334_sk: {{ (.Files.Get "certs/msp/keystore/ae2cbdd5ed5a1960096ff0430d981bc86a91f7a09b84acbe6261602039b04334_sk") | b64enc}}
  peer0.org1-cert.pem: {{ (.Files.Get "certs/msp/signcerts/peer0.org1-cert.pem") | b64enc}}
  tlsca.org1-cert.pem: {{ (.Files.Get "certs/msp/tlscacerts/tlsca.org1-cert.pem") | b64enc}}
