---
apiVersion: v1
kind: Secret
metadata:
  name: msp-config-{{ .Values.global.org.name }}-{{ .Values.global.peer.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/peers/peer0.%s/**" .Values.global.org.name .Values.global.org.name }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}