apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.org.name }}-{{ .Values.global.peer.name }}
  labels:
    run: {{ template "blockchain-peer.name" .}}
    app: {{ .Values.global.org.name }}-{{ .Values.global.peer.name }}
    chart: {{ template "blockchain-peer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports: {{ include "service.ports" . | indent 2}}
  selector:
    app: {{ .Values.global.org.name }}-{{ .Values.global.peer.name }}
    release: {{ .Release.Name }}
