---
apiVersion: v1
kind: Pod
metadata:
  name: utils
spec:
  restartPolicy: "Never"
  volumes:
  - name: dockersocket
    hostPath:
      path: /var/run/docker.sock
  - name: composer-credentials
    hostPath:
      path: /composer
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-orderer.pon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer.pon
    spec:
      volumes:
      - name: shared
        hostPath:
          path: /tmp

      containers:
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: blockchain-ca.pon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ca.pon
    spec:
      containers:
      - name: ca.pon
        image: ibmblockchain/fabric-ca:1.0.6
        command: ["sh", "-c", "sleep 1 && while [ ! -f /fabric-config/ ]; do echo Waiting for crypto config to be loaded; sleep 1; done; fabric-ca-server start -c ${CONFIGYAML}"]
        env:
        - name: CONFIGYAML
          value: /shared/cas/ca.yaml
        - name: FABRIC_CA_SERVER_CA_CERTFILE
          value: /fabric-config/crypto-config/peerOrganizations/ca/ca.pon-cert.pem
        - name: FABRIC_CA_SERVER_CA_KEYFILE
          value: /mnt/crypto-config/peerOrganizations/ca/b76ef2f0d4df95adec8501a85b09df153dd1d36c9982c98936b1878a28be321c_sk
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
        - name: FABRIC_CA_SERVER_TLS_CERTFILE
          value: /certs/ca0a-cert.pem
        - name: FABRIC_CA_SERVER_TLS_KEYFILE
          value: /certs/ca0a-key.pem
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
        - mountPath: /shared
          name: shared
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
    name: blockchain-peer0.pon
spec:
    serviceName: blockchain-peer0.pon
    replicas: 1
    template:
        metadata:
            labels:
                tier: peer0.pon
                vol: peer0.pon-pv
        spec:
            terminationGracePeriodSeconds: 10
            volumes:
            - name: dockersocket
              hostPath:
                path: /var/run/docker.sock
            containers:
                - name: peer0.pon
                  image: ibmblockchain/fabric-peer:1.0.6
                  imagePullPolicy: Always
                  command: ["sh", "-c", "sleep 1 && while [ ! -f /fabric-config/ ]; do echo Waiting for crypto config to be loaded; sleep 1; done; peer node start --peer-defaultchain=false"]
                  env:
                  - name: CORE_PEER_ADDRESSAUTODETECT
                    value: "true"
                  - name: CORE_PEER_NETWORKID
                    value: nid1
                  - name: CORE_PEER_ADDRESS
                    value: blockchain-peer0.pon:5010
                  - name: CORE_PEER_LISTENADDRESS
                    value: 0.0.0.0:5010
                  - name: CORE_PEER_EVENTS_ADDRESS
                    value: 0.0.0.0:5011
                  - name: CORE_PEER_GOSSIP_BOOTSTRAP
                    value: blockchain-peer0.pon:5010
                  - name: CORE_PEER_GOSSIP_ORGLEADER
                    value: "true"
                  - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
                    value: "true"
                  - name: CORE_PEER_COMMITTER_ENABLED
                    value: "true"
                  - name: CORE_PEER_PROFILE_ENABLED
                    value: "true"
                  - name: CORE_PEER_DISCOVERY_PERIOD
                    value: 60s
                  - name: CORE_PEER_DISCOVERY_TOUCHPERIOD
                    value: 60s
                  - name: CORE_VM_ENDPOINT
                    value: unix:///host/var/run/docker.sock
                  - name: CORE_PEER_LOCALMSPID
                    value: kpm-ponMSP
                  - name: CORE_PEER_MSPCONFIGPATH
                    value: /fabric-config/crypto-config/peerOrganizations/peers/peer0.pon/msp/
                  - name: CORE_LOGGING_LEVEL
                    value: debug
                  - name: CORE_LOGGING_PEER
                    value: debug
                  - name: CORE_LOGGING_CAUTHDSL
                    value: debug
                  - name: CORE_LOGGING_GOSSIP
                    value: debug
                  - name: CORE_LOGGING_LEDGER
                    value: debug
                  - name: CORE_LOGGING_MSP
                    value: info
                  - name: CORE_LOGGING_POLICIES
                    value: debug
                  - name: CORE_LOGGING_GRPC
                    value: debug
                  - name: CORE_PEER_TLS_ENABLED
                    value: "false"
                  - name: CORE_LEDGER_STATE_STATEDATABASE
                    # value: goleveldb
                    value: CouchDB
                  - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
                    value: blockchain-peer0.pon.couchdb:5984
                  - name: PEER_CFG_PATH
                    value: /fabric-config/crypto-config/peerOrganizations/peers/peer0.pon
                  - name: FABRIC_CFG_PATH
                    value: /fabric-config/
                  - name: ORDERER_URL
                    value: blockchain-orderer.kpm-pon:31010
                  - name: GODEBUG
                    value: "netdns=go"
                  volumeMounts:
                    - name: shared
                      mountPath: /shared
                    - name: dockersocket
                      mountPath: /host/var/run/docker.sock
                    - name: peer0.pon-pv
                      mountPath: /var/hyperledger/production
    volumeClaimTemplates:
        - metadata:
            name: peer0.pon-pv
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 1G
              selector:
                matchLabels:
                  vol: peer0.pon-pv
              storageClassName: ""
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
    name: blockchain-peer0.pon.couchdb
spec:
    serviceName: blockchain-peer0.pon.couchdb
    replicas: 1
    template:
        metadata:
            labels:
                tier: peer0.pon.couchdb
                vol: bc-peer0.pon.couchdb-pv
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: blockchain-peer0.pon.couchdb
                  image: ibmblockchain/fabric-couchdb:1.0.6
                  env:
                  - name: DB_URL
                    value: http://localhost:5984/member_db
                  volumeMounts:
                    - name: bc-peer0.pon.couchdb-pv
                      mountPath: /opt/couchdb/data
    volumeClaimTemplates:
        - metadata:
            name: bc-peer0.pon.couchdb-pv
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 1G
              selector:
                matchLabels:
                  vol: bc-peer0.pon.couchdb-pv
              storageClassName: ""