---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca
  labels:
    run: blockchain-ca
spec:
  type: NodePort
  selector:
    name: ca
  ports:
  - protocol: TCP
    port: 7054
    nodePort: 30000
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    port: 31010
    nodePort: 31010
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ponpeer
  labels:
    run: blockchain-ponpeer
    tier: ponpeer
spec:
  type: NodePort
  selector:
    tier: ponpeer
  ports:
  - protocol: TCP
    port: 5010
    nodePort: 30210
    name: grpc
  - protocol: TCP
    port: 5011
    nodePort: 30211
    name: events
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-couchdb2
  labels:
    run: blockchain-couchdb2
    tier: couchdb2
spec:
  type: NodePort
  selector:
    tier: couchdb2
  ports:
  - protocol: TCP
    port: 5984
    nodePort: 31984
    name: couchdb2
