---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ca
  labels:
    run: blockchain-ca
spec:
  type: NodePort
  selector:
    name: ca
  ports:
  - protocol: TCP
    port: 7054
    nodePort: 30000
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-orderer
  labels:
    run: blockchain-orderer
spec:
  type: NodePort
  selector:
    name: orderer
  ports:
  - protocol: TCP
    port: 31010
    nodePort: 31010
    name: grpc
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-kpm-ponpeer1
  labels:
    run: blockchain-kpm-ponpeer1
spec:
  type: NodePort
  selector:
    name: kpm-ponpeer1
  ports:
  - protocol: TCP
    port: 5010
    nodePort: 30110
    name: grpc
  - protocol: TCP
    port: 5011
    nodePort: 30111
    name: events
---
apiVersion: v1
kind: Service
metadata:
  name: blockchain-ponpeer1
  labels:
    run: blockchain-ponpeer1
spec:
  type: NodePort
  selector:
    name: ponpeer1
  ports:
  - protocol: TCP
    port: 5010
    nodePort: 30210
    name: grpc
  - protocol: TCP
    port: 5011
    nodePort: 30211
    name: events
