---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: orderer-kpm-pon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: orderer-kpm-pon
    spec:
      containers:
      - name: orderer-kpm-pon
        image: ibmblockchain/fabric-orderer:1.0.6
        command: ["sh", "-c", "sleep 5 && while [ ! -f /fabric-config/production.block ]; do echo Waiting for crypto to be loaded; sleep 1; done; orderer"]
        env:
        - name: ORDERER_CFG_PATH
          value: /fabric-config
        - name: ORDERER_GENERAL_LEDGERTYPE
          value: file
        - name: ORDERER_FILELEDGER_LOCATION
          value: /mnt/ledger/orderer1
        - name: ORDERER_GENERAL_BATCHTIMEOUT
          value: 1s
        - name: ORDERER_GENERAL_BATCHSIZE_MAXMESSAGECOUNT
          value: "10"
        - name: ORDERER_GENERAL_MAXWINDOWSIZE
          value: "1000"
        - name: ORDERER_GENERAL_ORDERERTYPE
          value: solo
        - name: ORDERER_GENERAL_LISTENADDRESS
          value: 0.0.0.0
        - name: ORDERER_GENERAL_LISTENPORT
          value: "7050"
        - name: ORDERER_GENERAL_LOGLEVEL
          value: debug
        - name: ORDERER_GENERAL_LOCALMSPDIR
          value: /fabric-config/msp
        - name: ORDERER_GENERAL_LOCALMSPID
          value: kpmOrdererMSP
        - name: ORDERER_GENERAL_GENESISMETHOD
          value: file
        - name: ORDERER_GENERAL_GENESISFILE
          value: /fabric-config/production.block
        - name: ORDERER_GENERAL_GENESISPROFILE
          value: initial
        - name: ORDERER_GENERAL_TLS_ENABLED
          value: "false"
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
          - name: orderer-fabric-config
            mountPath: /fabric-config
      volumes:
        - name: orderer-fabric-config
          emptyDir: {}
      nodeSelector:
        environment: kpm-pon
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ca-kpm-pon
spec:
  replicas: 1
  template:
    metadata:
      labels:
        name: ca-kpm-pon
    spec:
      containers:
      - name: ca-kpm-pon
        image: ibmblockchain/fabric-ca:1.0.6
        command: ["sh", "-c", "sleep 1 && while [ ! -f /fabric-config/ca/ca.kpm-pon-cert.pem ]; do echo Waiting for crypto config to be loaded; sleep 1; done; fabric-ca-server start --ca.name ca-kpm-pon --ca.certfile /fabric-config/ca/ca.kpm-pon-cert.pem --ca.keyfile /fabric-config/ca/52da9f2222ce0c6133e0c3ad5565d8af0acea880058c45f372cc2b45334cb52e_sk -b admin:adminpw -d"]
        env:
#        - name: FABRIC_CA_SERVER_CA_CERTFILE
#          value: /fabric-config/ca/ca.kpm-pon-cert.pem
#        - name: FABRIC_CA_SERVER_CA_KEYFILE
#          value: /fabric-config/ca/52da9f2222ce0c6133e0c3ad5565d8af0acea880058c45f372cc2b45334cb52e_sk
        - name: FABRIC_CA_SERVER_DEBUG
          value: "true"
        - name: FABRIC_CA_SERVER_TLS_ENABLED
          value: "false"
#        - name: FABRIC_CA_SERVER_TLS_CERTFILE
#          value: /fabric-config/ca/ca.kpm-pon-cert.pem
#        - name: FABRIC_CA_SERVER_TLS_KEYFILE
#          value: /fabric-config/ca/52da9f2222ce0c6133e0c3ad5565d8af0acea880058c45f372cc2b45334cb52e_sk
        - name: GODEBUG
          value: "netdns=go"
        volumeMounts:
          - name: ca-fabric-config
            mountPath: /fabric-config
      volumes:
        - name: ca-fabric-config
          emptyDir: {}
      nodeSelector:
        environment: kpm-pon
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
    name: peer0-kpm-pon
spec:
    serviceName: peer0-kpm-pon
    replicas: 1
    template:
        metadata:
            labels:
                tier: peer0-kpm-pon
                vol: peer0-kpm-pon-pv
        spec:
            terminationGracePeriodSeconds: 10
            volumes:
            - name: dockersocket
              hostPath:
                path: /var/run/docker.sock
            - name: peer-fabric-config
              emptyDir: {}
            containers:
                - name: peer0-kpm-pon
                  image: ibmblockchain/fabric-peer:1.0.6
                  imagePullPolicy: Always
                  command: ["sh", "-c", "sleep 1 && while [ ! -d /fabric-config/msp ]; do echo Waiting for crypto config to be loaded...; sleep 1; done; peer node start --peer-defaultchain=false"]
                  env:
                  - name: CORE_PEER_ADDRESSAUTODETECT
                    value: "true"
                  - name: CORE_PEER_NETWORKID
                    value: nid1
                  - name: CORE_PEER_ADDRESS
                    value: peer0-kpm-pon:5010
                  - name: CORE_PEER_LISTENADDRESS
                    value: 0.0.0.0:5010
                  - name: CORE_PEER_EVENTS_ADDRESS
                    value: 0.0.0.0:5011
                  - name: CORE_PEER_GOSSIP_BOOTSTRAP
                    value: peer0-kpm-pon:5010
                  - name: CORE_PEER_GOSSIP_ORGLEADER
                    value: "true"
                  - name: CORE_PEER_GOSSIP_SKIPHANDSHAKE
                    value: "true"
                  - name: CORE_PEER_COMMITTER_ENABLED
                    value: "true"
                  - name: CORE_PEER_PROFILE_ENABLED
                    value: "true"
                  - name: CORE_PEER_DISCOVERY_PERIOD
                    value: 60s
                  - name: CORE_PEER_DISCOVERY_TOUCHPERIOD
                    value: 60s
                  - name: CORE_VM_ENDPOINT
                    value: unix:///host/var/run/docker.sock
                  - name: CORE_PEER_LOCALMSPID
                    value: kpm-ponMSP
                  - name: CORE_PEER_MSPCONFIGPATH
                    value: /fabric-config/msp
                  - name: CORE_LOGGING_LEVEL
                    value: debug
                  - name: CORE_LOGGING_PEER
                    value: debug
                  - name: CORE_LOGGING_CAUTHDSL
                    value: debug
                  - name: CORE_LOGGING_GOSSIP
                    value: debug
                  - name: CORE_LOGGING_LEDGER
                    value: debug
                  - name: CORE_LOGGING_MSP
                    value: info
                  - name: CORE_LOGGING_POLICIES
                    value: debug
                  - name: CORE_LOGGING_GRPC
                    value: debug
                  - name: CORE_PEER_TLS_ENABLED
                    value: "false"
                  - name: CORE_LEDGER_STATE_STATEDATABASE
                    # value: goleveldb
                    value: CouchDB
                  - name: CORE_LEDGER_STATE_COUCHDBCONFIG_COUCHDBADDRESS
                    value: peer0-kpm-pon-couchdb:5984
                  - name: PEER_CFG_PATH
                    value: peer_config/
                  - name: FABRIC_CFG_PATH
                    value: /etc/hyperledger/fabric/
                  - name: ORDERER_URL
                    value: orderer-kpm-pon:7050
                  - name: GODEBUG
                    value: "netdns=go"
                  volumeMounts:
                    - name: dockersocket
                      mountPath: /host/var/run/docker.sock
                    - name: peer0-kpm-pon-pv
                      mountPath: /var/hyperledger/production
                    - name: peer-fabric-config
                      mountPath: /fabric-config
            nodeSelector:
                environment: kpm-pon
    volumeClaimTemplates:
        - metadata:
            name: peer0-kpm-pon-pv
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 1G
              selector:
                matchLabels:
                  vol: peer0-kpm-pon-pv
              storageClassName: ""
---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
    name: peer0-kpm-pon-couchdb
spec:
    serviceName: peer0-kpm-pon-couchdb
    replicas: 1
    template:
        metadata:
            labels:
                tier: peer0-kpm-pon-couchdb
                vol: bc-peer0-kpm-pon-couchdb-pv
        spec:
            terminationGracePeriodSeconds: 10
            containers:
                - name: peer0-kpm-pon-couchdb
                  image: ibmblockchain/fabric-couchdb:1.0.6
                  env:
                  - name: DB_URL
                    value: http://localhost:5984/member_db
                  volumeMounts:
                    - name: bc-peer0-kpm-pon-couchdb-pv
                      mountPath: /opt/couchdb/data
            nodeSelector:
              environment: kpm-pon
    volumeClaimTemplates:
        - metadata:
            name: bc-peer0-kpm-pon-couchdb-pv
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 1G
              selector:
                matchLabels:
                  vol: bc-peer0-kpm-pon-couchdb-pv
              storageClassName: ""
