apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-composer-connection-profile
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
data:
  connection.json: |-
    {
    "type":        "hlfv1",
    "orderers":    [
    {
      "url": "grpc://{{ .Values.global.network.orderer_cluster_IP }}:{{ .Values.global.network.orderer_port }}"
    }
    ],
    "ca":          {
      "url":  "http://{{ .Values.global.network.actual_cluster_IP }}:{{ .Values.global.network.ca_port }}",
      "name": {{ quote .Values.global.network.ca_name }}
    },
    "peers":       [
    {
      "requestURL": "grpc://{{ .Values.global.network.actual_cluster_IP }}:{{ .Values.global.network.peer_port }}",
      "eventURL":   "grpc://{{ .Values.global.network.actual_cluster_IP }}:{{ .Values.global.network.peer_event_port }}"
    }
    ],
    "keyValStore": "/home/composer/.composer-credentials",
    "channel":     {{quote .Values.global.blockchain.channel }},
    "mspID":       "{{ .Values.global.organization.name }}MSP",
    "timeout":     "300"
    }