apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.application.server.name }}
  labels:
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: NodePort
  ports:
  - protocol: TCP
    name: http
    port: {{ default "8080" .Values.global.application.server.port }}
    nodePort: {{ default "31001" .Values.global.application.server.public_port }}
  selector:
   app: {{ .Values.global.application.server.name }}