apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.application.server.name }}
spec:
  type: LoadBalancer
  ports:
  - name: http
    port: {{ default "8080" .Values.global.application.server.port }}
    targetPort: {{ default "8080" .Values.global.application.server.port }}
  selector:
   app: {{ .Values.global.application.server.name }}