apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Values.global.application.couchdb.name }}
    chart: {{ .Chart.Name }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  name: {{ .Values.global.application.couchdb.name }}
spec:
  ports:
  - name: http
    port: {{ default "5984" .Values.global.application.couchdb.port }}
    targetPort: {{ default "5984" .Values.global.application.couchdb.port }}
  selector:
    app: {{ .Values.global.application.couchdb.name }}