##
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Use a json formatter and minify
# https://jsonformatter.org/

Feature: CarrierMember feature test

  Background:
    Given I have deployed the business network definition ..
    And I have added the following participants of type org.digitalcmr.CarrierMember
      """
        {"$class":"org.digitalcmr.CarrierMember", "userID": "harry@koopman.org", "userName": "willem", "firstName": "willem", "lastName": "compy", "address": {"$class": "org.digitalcmr.Address", "name": "willem compy", "street": "compenstraat", "houseNumber": "18", "city": "Amsterdam", "zipCode": "9867UG", "country": "Netherlands", "latitude": 52.2443, "longitude": 65.2323, "id":"id"},"org":"koopman"}
      """
    And I have issued the participant org.digitalcmr.CarrierMember#harry@koopman.org with the identity Harry
    And I have added the following assets of type org.digitalcmr.Vehicle
      """
      [
        {"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Audi","model":"A1","type":"sportback","ecmrs":[],"odoMeterReading":0,"plateNumber":"AV198RX"},
        {"$class":"org.digitalcmr.Vehicle","vin":"B12345VIN","manufacturer":"Audi","model":"A1","type":"sportback","ecmrs":[],"odoMeterReading":0,"plateNumber":"AV198RX"}
      ]
      """
    And I have added the following assets of type org.digitalcmr.TransportOrder
      """
      [
        {"$class":"org.digitalcmr.TransportOrder","orderID":"A12345ORDER","status":"OPEN","owner":"leaseplan","carrier":"koopman","issueDate":0,"orderRef":"orderRef","goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"ecmrs":[]},
        {"$class":"org.digitalcmr.TransportOrder","orderID":"B12345ORDER","status":"OPEN","owner":"notLeaseplan","carrier":"notKoopman","issueDate":0,"orderRef":"orderRef","goods":[{"$class":"org.digitalcmr.Good","source":"NotAmsterdamcompound","recipient":"NotCardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"ecmrs":[]},
        {"$class":"org.digitalcmr.TransportOrder","orderID":"C12345ORDER","status":"IN_PROGRESS","owner":"leaseplan","carrier":"koopman","issueDate":0,"orderRef":"orderRef","goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"ecmrs":[]},
        {"$class":"org.digitalcmr.TransportOrder","orderID":"D12345ORDER","status":"OPEN","owner":"leaseplan","carrier":"koopman","issueDate":0,"orderRef":"orderRef","goods":[{"source":"amsterdamcompound","recipient":"cardealer","loadingAddress":{"name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"vehicle":{"vin":"A12345VIN","manufacturer":"Audi","model":"A1","type":"sportback","ecmrs":[],"odoMeterReading":0,"plateNumber":"AV198RX"},"description":"vehicle","weight":1500,"pickupWindow":{"startDate":1502834400000,"endDate":1502834400000},"deliveryWindow":{"startDate":1502834400000,"endDate":1502834400000}},{"source":"amsterdamcompound","recipient":"cardealer","vehicle":{"vin":"B12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"pickupWindow":{"startDate":1502834400000,"endDate":1502834400000},"deliveryWindow":{"startDate":1502834400000,"endDate":1502834400000},"loadingAddress":{"name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123}}],"ecmrs":[]}
      ]
      """
    And I have added the following assets of type org.digitalcmr.ECMR
      """
      [
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readWrongStatus","status":"CREATED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"A12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readAll","status":"IN_TRANSIT","compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readNotCarrier","status":"LOADED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"B12345ORDER","owner":"notLeaseplan","source":"notAmsterdamcompound","carrier":"notKopman","recipient":"notCardealer","transporter":"harry@koopman.org","recipientMember":"james@notCardelear.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"moveInTransit","status":"LOADED","compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"noCompoundSignature","status":"LOADED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readNotTransporter","status":"LOADED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"B12345ORDER","owner":"notLeaseplan","source":"notAmsterdamcompound","carrier":"koopman","recipient":"notCardealer","transporter":"sam@notKoopman.org","recipientMember":"james@notCardelear.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"moveToDelivered","status":"IN_TRANSIT","carrierLoadingSignature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"noCarrierLoadingSignature","status":"IN_TRANSIT","compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"},
        {"$class":"org.digitalcmr.ECMR","ecmrID":"delivered","status":"DELIVERED","carrierDeliverySignature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"carrierLoadingSignature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      ]
      """

  Scenario: Harry should be able to read all of his ECMRs where he is transporter, his org is carrier and the status is anything but CREATED
    When I use the identity Harry
    Then I should have the following assets of type org.digitalcmr.ECMR
      """
      [
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readAll","status":"IN_TRANSIT","compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      ]
      """

  Scenario: Harry should not be able to read ECMRs that have status CREATED
    When I use the identity Harry
    Then I should not have the following assets of type org.digitalcmr.ECMR
      """
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readWrongStatus","status":"CREATED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"A12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      """

  Scenario: Harry should not be able to read ECMRs where he is not the carrier
    When I use the identity Harry
    Then I should not have the following assets of type org.digitalcmr.ECMR
      """
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readNotCarrier","status":"LOADED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"B12345ORDER","owner":"notLeaseplan","source":"notAmsterdamcompound","carrier":"notKopman","recipient":"notCardealer","transporter":"harry@koopman.org","recipientMember":"james@notCardelear.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      """

  Scenario: Harry should not be able to read ECMRs where he is not the transporter
    When I use the identity Harry
    Then I should not have the following assets of type org.digitalcmr.ECMR
      """
        {"$class":"org.digitalcmr.ECMR","ecmrID":"readNotTransporter","status":"LOADED","agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"B12345ORDER","owner":"notLeaseplan","source":"notAmsterdamcompound","carrier":"koopman","recipient":"notCardealer","transporter":"sam@notKoopman.org","recipientMember":"james@notCardelear.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      """

  Scenario: Harry should be able to update an ECMR by using the UpdateEcmrStatusToInTransit transaction to IN_TRANSIT when his org is carrier, he is the transporter and the status is LOADED
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToInTransit
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToInTransit","ecmr":"moveInTransit","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should have the following asset of type org.digitalcmr.ECMR
      """
        {"$class":"org.digitalcmr.ECMR","ecmrID":"moveInTransit","status":"IN_TRANSIT","carrierLoadingSignature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      """

  # it should never happen based on smart-contract rules
  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToInTransit transaction to IN_TRANSIT when there is no CompoundAdmin signature
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToInTransit
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToInTransit","ecmr":"noCompoundSignature","signature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /Attempt to set the status on IN_TRANSIT before the compound admin signed/

  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToInTransit transaction to IN_TRANSIT when his org is not carrier
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToInTransit
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToInTransit","ecmr":"readNotCarrier","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /does not exist/

  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToInTransit transaction to IN_TRANSIT when he is not the transporter
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToInTransit
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToInTransit","ecmr":"readNotTransporter","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /does not exist/

  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToInTransit transaction to IN_TRANSIT when the status is not LOADED
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToInTransit
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToInTransit","ecmr":"delivered","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /Invalid transaction. Trying to set status IN_TRANSIT/

  Scenario: Harry should be able to update an ECMR by using the UpdateEcmrStatusToDelivered transaction to IN_TRANSIT when his org is carrier, he is the transporter and the status is LOADED
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToDelivered
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToDelivered","transportOrder":"A12345ORDER","ecmr":"moveToDelivered","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should have the following asset of type org.digitalcmr.ECMR
      """
        {"$class":"org.digitalcmr.ECMR","ecmrID":"moveToDelivered","status":"DELIVERED","carrierDeliverySignature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"carrierLoadingSignature":{"certificate":"harry@koopman.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"compoundSignature":{"certificate":"willem@amsterdamcompound.org","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"agreementTerms":"agreement terms here","agreementTermsSec":"agreement terms sec","legalOwnerRef":"ASD213123S","carrierRef":"H2238723VASD","recipientRef":"SDADHGA21312312","orderID":"C12345ORDER","owner":"leaseplan","source":"amsterdamcompound","carrier":"koopman","recipient":"cardealer","transporter":"harry@koopman.org","recipientMember":"rob@cardealer.org","creation":{"$class":"org.digitalcmr.Creation","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":52.377698,"longitude":4.896555},"date":1502402400000},"loading":{"$class":"org.digitalcmr.Loading","address":{"$class":"org.digitalcmr.Address","name":"Amsterdam Compound","street":"Compoundstraat","houseNumber":"21","city":"Assen","zipCode":"9976ZH","country":"Netherlands","latitude":43.1927,"longitude":23.3249},"actualDate":1502488800000},"delivery":{"$class":"org.digitalcmr.Delivery","address":{"$class":"org.digitalcmr.Address","name":"Rob el Caro","street":"De straat","houseNumber":"302","city":"Almere","zipCode":"6736AE","country":"Netherlands","latitude":51.917153,"longitude":4.474623},"actualDate":1502834400000},"issueDate":0,"issuedBy":"koopman","carrierComments":"","documents":[],"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}],"legalOwnerInstructions":"string","paymentInstructions":"string","payOnDelivery":"string"}
      """

  # it should never happen based on smart-contract rules
  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToDelivered transaction to DELIVERED when there is no CompoundAdmin or Carrier loading signature
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToDelivered
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToDelivered","transportOrder":"A12345ORDER","ecmr":"noCarrierLoadingSignature","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /Transaction is not valid. Attempt to set the status on DELIVERED/

  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToDelivered transaction to DELIVERED when his org is not carrier
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToDelivered
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToDelivered","transportOrder":"A12345ORDER","ecmr":"readNotCarrier","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /does not exist/

  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToDelivered transaction to DELIVERED when he is not the transporter
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToDelivered
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToDelivered","transportOrder":"A12345ORDER","ecmr":"readNotTransporter","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /does not exist/

  Scenario: Harry should not be able to update an ECMR by using the UpdateEcmrStatusToDelivered transaction to DELIVERED when the status is not IN_TRANSIT
    When I use the identity Harry
    And I submit the following transaction of type org.digitalcmr.UpdateEcmrStatusToDelivered
      """
        {"$class":"org.digitalcmr.UpdateEcmrStatusToDelivered","transportOrder":"A12345ORDER","ecmr":"moveInTransit","signature":{"certificate":"something","timestamp":1512652279289,"generalRemark":{"comments":"something"}},"goods":[{"$class":"org.digitalcmr.Good","source":"amsterdamcompound","recipient":"cardealer","vehicle":{"$class":"org.digitalcmr.Vehicle","vin":"A12345VIN","manufacturer":"Mercedes","model":"SLK","type":"Station","ecmrs":[],"odoMeterReading":0,"plateNumber":"I827YE"},"description":"vehicle","weight":1800,"loadingAddress":{"$class":"org.digitalcmr.Address","name":"loading address","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"deliveryAddress":{"$class":"org.digitalcmr.Address","name":"delivery adress","street":"een straat","houseNumber":"41","city":"Groningen","zipCode":"7811 HC","country":"netherlands","longitude":124,"latitude":123},"pickupWindow":{"$class":"org.digitalcmr.DateWindow","startDate":"1502834400000","endDate":"1502834400000"},"deliveryWindow":{"startDate":"1502834400000","endDate":"1502834400000"}}]}
      """
    Then I should get an error matching /Invalid transaction. Trying to set status DELIVERED/