---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: privatedb-pv
spec:
    capacity:
        storage: 100M
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/var/privatedb"