---
apiVersion: v1
kind: Service
metadata:
  name: privatedb
  labels:
    app: privatedb
    tier: db
spec:
  type: NodePort
  selector:
    tier: db
  ports:
  - protocol: TCP
    port: 5984
    name: http