kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer0-test-pvc
  labels:
    app: blockchain-test
    chart: "test-0.1.0"
    release: "blockchain"
    heritage: "Tiller"
spec:
  accessModes:
  - "ReadWriteOnce"
  resources:
    requests:
      storage: 1G
  selector:
    matchLabels:
      vol: peer0-test-pv