---
apiVersion: v1
kind: Service
metadata:
  name: server-all
  labels:
    run: server-all
spec:
  type: NodePort
  selector:
    tier: server-all
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31021
    name: http
  - protocol: TCP
    port: 443
    nodePort: 31423
    name: https