apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.org.name }}-{{ .Values.global.ca.name }}-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  FABRIC_CA_SERVER_DEBUG: "true"
  FABRIC_CA_SERVER_TLS_ENABLED: "false"
  FABRIC_CA_SERVER_CA_CERTFILE: /fabric-config/ca/{{- include "ca.certificate" . }}
  FABRIC_CA_SERVER_CA_KEYFILE: /fabric-config/ca/{{ include "ca.keystore" . }}
  GODEBUG: "netdns=go"