apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Values.global.ca.name }}-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "1"
    "helm.sh/hook-delete-policy": "before-hook-creation"
  labels:
{{ include "labels.standard" . | indent 4 }}
data:
  FABRIC_CA_SERVER_DEBUG: "true"
  FABRIC_CA_SERVER_TLS_ENABLED: "false"
  FABRIC_CA_SERVER_TLS_CERTFILE: /fabric-config/ca/ca.org1-cert.pem
  FABRIC_CA_SERVER_TLS_KEYFILE: /fabric-config/ca/893310e916a6534671a65c141b6661611330f9c261ee7106f238c5ce7861191b_sk
  GODEBUG: "netdns=go"