apiVersion: v1
kind: Secret
metadata:
  name: ca-config-{{ .Values.global.ca.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
  893310e916a6534671a65c141b6661611330f9c261ee7106f238c5ce7861191b_sk: {{ (.Files.Get "certs/ca/893310e916a6534671a65c141b6661611330f9c261ee7106f238c5ce7861191b_sk") | b64enc}}
  ca.org1-cert.pem: {{ (.Files.Get "certs/ca/ca.org1-cert.pem") | b64enc}}
