apiVersion: v1
kind: Secret
metadata:
  name: ca-config-{{ include "blockchain-ca.fullname" . }}
type: Opaque
data:
  260dc7753aa8cec9275e703771d65a4127675368e98c95463eafa0b9a9bb3992_sk: {{ (.Files.Get "certs/ca/260dc7753aa8cec9275e703771d65a4127675368e98c95463eafa0b9a9bb3992_sk") | b64enc}}
  ca.kpm-pon-cert.pem: {{ (.Files.Get "certs/ca/ca.kpm-pon-cert.pem") | b64enc}}
