kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ template "blockchain-peer.fullname" . }}-pvc
  labels:
    app: {{ template "blockchain-peer.name" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  accessModes:
  - {{ .Values.persistence.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.persistence.size }}
  selector:
    matchLabels:
      vol: peer0-test-pv