apiVersion: v1
kind: Secret
metadata:
  name: msp-config-{{ include "blockchain-peer.fullname" . }}
type: Opaque
data:
  admin-kpm-pon-cert.pem: {{ (.Files.Get "certs/msp/admincerts/admin-kpm-pon-cert.pem") | b64enc}}
  ca.kpm-pon-cert.pem: {{ (.Files.Get "certs/msp/cacerts/ca.kpm-pon-cert.pem") | b64enc}}
  tlsca.kpm-pon-cert.pem: {{ (.Files.Get "certs/msp/tlscacerts/tlsca.kpm-pon-cert.pem") | b64enc}}
