---
apiVersion: v1
kind: Service
metadata:
  name: app-server
  labels:
    run: app-server
spec:
  type: NodePort
  selector:
    name: app-server
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31001
    name: http