---
apiVersion: v1
kind: Pod
metadata:
  name: app-server
  labels:
    name: app-server
spec:
  restartPolicy: "Always"
  containers:
  - name: app-server
    image: registry.eu-gb.bluemix.net/apps/digitalcmr_server
    imagePullPolicy: Always
    imagePullSecrets:
    - name: bluemix-uk-registry
    command: ["sh", "-c", "sleep 30 && npm start"]
    env:
    - name: NODE_ENV
      value: staging
    - name: HOST
      value: "0.0.0.0"
    - name: PORT
      value: "8080"
