{{ if .Values.global.orderer.deployorderer }}
apiVersion: v1
kind: Secret
metadata:
  name: orderer-config-{{ .Values.global.org.name }}-{{ .Values.global.orderer.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/ordererOrganizations/%s/orderers/orderer.%s/**" .Values.global.org.name .Values.global.org.name }}
{{- $genesisfile := printf "environment/%s" .Values.global.genesisfilename }}
{{- $networkfile := printf "environment/%s" .Values.global.networkfilename }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{ .Values.global.genesisfilename | indent 2  }}: {{ (.Files.Get $genesisfile) | b64enc }}
{{ .Values.global.networkfilename | indent 2 }}: {{ (.Files.Get $networkfile) | b64enc }}
{{ end }}
