apiVersion: v1
kind: PersistentVolume
metadata:
    name: couchdb-pv
    labels:
      vol: couchdb-pv
spec:
    capacity:
        storage: 1Gi
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
        path: "/var/couchdb-pv"