{{ if .Values.global.orderer.deployorderer }}
apiVersion: v1
kind: Secret
metadata:
  name: orderer-config-{{ .Values.global.org.name }}-{{ .Values.global.orderer.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ $path := printf "certs/orderers/%s/**" .Values.global.org.name}}
{{- (.Files.Glob $path).AsSecrets | indent 2 }}
  genericgenesis.block: {{ (.Files.Get "certs/genericgenesis.block") | b64enc}}
  genericnetwork.tx: {{ (.Files.Get "certs/genericnetwork.tx") | b64enc}}
{{ end }}
