---
apiVersion: v1
kind: Pod
metadata:
  name: composer-identity-import
spec:
  restartPolicy: "Never"
  volumes:
  - name: composer-credentials
    hostPath:
      path: /composer
  - name: shared
    hostPath:
      path: /tmp
  containers:
  - name: composer-identity-import
    image: hyperledger/composer-cli:0.13.2
    imagePullPolicy: Always
    command: ["sh", "-c", "composer identity import -p hlfv1 -u PeerAdmin -c /fabric-config/crypto-config/peerOrganizations/pon/users/Admin@pon/msp/signcerts/Admin@pon-cert.pem -k /fabric-config/crypto-config/peerOrganizations/pon/users/Admin@pon/msp/keystore/key.pem"]
    env:
    - name: COMPOSER_CONFIG
      value: >
        {
          "defaultConnectionProfile": "hlfv1",
          "connectionProfiles": {
            "hlfv1": {
              "type": "hlfv1",
              "orderers": [
                  {
                      "url": "grpc://blockchain-orderer.pon:31010"
                  }
              ],
              "ca": {
                  "url": "http://blockchain-ca.pon:7054",
                  "name": "ca.pon"
              },
              "peers": [
                  {
                      "requestURL": "grpc://blockchain-peer0.pon:5010",
                      "eventURL": "grpc://blockchain-peer0.pon:5011"
                  }
              ],
              "keyValStore": "/home/composer/.hfc-key-store",
              "channel": "composerchannel",
              "mspID": "kpm-ponMSP",
              "timeout": "300"
            }
          },
          "credentials": {
            "hlfv1": {
              "PeerAdmin": "notneeded",
              "admin": "adminpw"
            }
          }
        }
    volumeMounts:
    - name: composer-credentials
      mountPath: /home
    - name: shared
      mountPath: /shared
      