---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: privatedb-kpm-pon-pv
    labels:
      vol: privatedb-kpm-pon-pv
spec:
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/var/privatedb-kpm-pon"