kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: couchdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      vol: couchdb-pv