{{ if .Values.global.orderer.deployorderer }}
apiVersion: v1
kind: Secret
metadata:
  name: create-channel-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := (printf "environment/crypto-config/peerOrganizations/%s/peers/peer0.%s/**" .Values.global.org.name .Values.global.org.name) }}
{{- $networkfile := printf "environment/%s" .Values.global.networkfilename }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{ .Values.global.networkfilename | indent 2 }}: {{ (.Files.Get $networkfile) | b64enc}}
{{end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: join-channel-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/users/admin-%s/**" .Values.global.org.name .Values.global.org.name }}
{{- $networkfile := printf "environment/%s" .Values.global.networkfilename }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{ .Values.global.networkfilename  | indent 2 }}: {{ (.Files.Get $networkfile)  | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-bna-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/users/admin-%s/**" .Values.global.org.name .Values.global.org.name }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
  digital-cmr-network.bna: {{ (.Files.Get "environment/digital-cmr-network.bna") | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: ca-config-{{ .Values.global.org.name }}-{{ .Values.global.ca.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/ca/**" .Values.global.org.name }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
---
  {{ if .Values.global.orderer.deployorderer }}
apiVersion: v1
kind: Secret
metadata:
  name: orderer-config-{{ .Values.global.org.name }}-{{ .Values.global.orderer.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/ordererOrganizations/%s/orderers/orderer.%s/**" .Values.global.org.name .Values.global.org.name }}
{{- $genesisfile := printf "environment/%s" .Values.global.genesisfilename }}
{{- $networkfile := printf "environment/%s" .Values.global.networkfilename }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
{{ .Values.global.genesisfilename | indent 2  }}: {{ (.Files.Get $genesisfile) | b64enc }}
{{ .Values.global.networkfilename | indent 2 }}: {{ (.Files.Get $networkfile) | b64enc }}
{{ end }}
---
apiVersion: v1
kind: Secret
metadata:
  name: msp-config-{{ .Values.global.org.name }}-{{ .Values.global.peer.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/peers/peer0.%s/**" .Values.global.org.name .Values.global.org.name }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}
