{{ if .Values.global.orderer.deployorderer }}
{{ $networkfile := printf "certs/" .Values.global.networkfilename}}
apiVersion: v1
kind: Secret
metadata:
  name: create-channel-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ $path := printf "certs/peers/%s/**" .Values.global.org.name}}
{{- (.Files.Glob $path).AsSecrets | indent 2 }}
  {{ .Values.global.networkfilename }}: {{ (.Files.Get $networkfile") | b64enc}}
{{end}}
---
apiVersion: v1
kind: Secret
metadata:
  name: join-channel-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ $path := printf "certs/users/%s/**" .Values.global.org.name}}
{{- (.Files.Glob $path).AsSecrets | indent 2 }}
  {{ .Values.global.networkfilename }}: {{ (.Files.Get $networkfile")  | b64enc}}
---
apiVersion: v1
kind: Secret
metadata:
  name: deploy-bna-config
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{ $path := printf "certs/users/%s/**" .Values.global.org.name}}
{{- (.Files.Glob $path).AsSecrets | indent 2 }}
  digital-cmr-network.bna: {{ (.Files.Get "certs/digital-cmr-network.bna") | b64enc}}