---
apiVersion: v1
kind: Service
metadata:
  name: server-kpm-all
  labels:
    run: server-kpm-all
spec:
  type: NodePort
  selector:
    tier: server-kpm-all
  ports:
  - protocol: TCP
    port: 8080
    nodePort: 31021
    name: http
  - protocol: TCP
    port: 443
    nodePort: 31463
    name: https