---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: peer0-couchdb-pv
  labels:
    vol: peer0-couchdb-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/peer0-kpm-all-couchdb"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: peer0-pv
  labels:
    vol: peer0-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: "/var/peer0-kpm-all"