---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer0-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      vol: peer0-pv
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: peer0-couchdb-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  selector:
    matchLabels:
      vol: peer0-couchdb-pv