---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: kpm-pon-credentials-pv
    labels:
      vol: kpm-pon-credentials-pv
spec:
    capacity:
        storage: 1G
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/var/.kpm-pon-credentials"