---
apiVersion: v1
kind: Pod
metadata:
  name: wipeshared
spec:
  restartPolicy: "Never"
  volumes:
  - name: pon-composer-credentials
    hostPath:
      path: "/composer"
  - name: peer0-pon-pv
    hostPath:
      path: "/var/peer0-pon"
  - name: bc-peer0-pon-couchdb-pv
    hostPath:
      path: "/var/peer0-pon-couchdb"
  - name: privatedb-pon-pv
    hostPath:
      path: "/var/privatedb-pon"
  - name: pon-fabric-config
    hostPath:
      path: "/fabric-config"
  - name: pon-credentials-pv
    hostPath:
      path: "/var/.composer-credentials"

  containers:
  - name: wipeshared
    image: ibmblockchain/fabric-tools:1.0.6
    imagePullPolicy: Always
    command: ["sh", "-c", "rm -rf /home/* /fabric-config/* /fabric-config-join-channel/* /privatedb-pon/* /peer0-pon/* /peer0-pon-couchdb/* /.composer-credentials/*"]
    volumeMounts:
    - name: pon-composer-credentials
      mountPath: /home/
    - name: privatedb-pon-pv
      mountPath: /privatedb-pon
    - name: peer0-pon-pv
      mountPath: /peer0-pon
    - name: bc-peer0-pon-couchdb-pv
      mountPath: /peer0-pon-couchdb
    - name: pon-fabric-config
      mountPath: /fabric-config
    - name: pon-credentials-pv
      mountPath: /.composer-credentials
    - name: joinchannel-pon-fabric-config
      mountPath: /fabric-config-join-channel
  nodeSelector:
    environment: pon