---
apiVersion: v1
kind: PersistentVolume
metadata:
    name: credentials-pv
    labels:
      vol: credentials-pv
spec:
    capacity:
        storage: 100M
    accessModes:
        - ReadWriteOnce
    persistentVolumeReclaimPolicy: Recycle
    hostPath:
        path: "/var/.composer-credentials"