apiVersion: v1
kind: Secret
metadata:
  name: ca-config-{{ .Values.global.org.name }}-{{ .Values.global.ca.name }}
  annotations:
    "helm.sh/hook": "pre-install"
    "helm.sh/hook-weight": "0"
    "helm.sh/hook-delete-policy": "before-hook-creation"
type: Opaque
data:
{{- $path := printf "environment/crypto-config/peerOrganizations/%s/ca/**" .Values.global.org.name }}
{{ (.Files.Glob $path).AsSecrets | indent 2 }}