---
apiVersion: v1
kind: Pod
metadata:
  name: api-doc
  labels:
    name: api-doc
spec:
  replicas: 1
  restartPolicy: "Always"
  containers:
  - name: api-doc
    image: registry.eu-gb.bluemix.net/koopman/digitalcmr_api_doc
    imagePullPolicy: Always
    imagePullSecrets:
    - name: bluemix-uk-registry
    command: ["sh", "-c", "./node_modules/.bin/ng serve -H 0.0.0.0 -e prod --disable-host-check"]
