---
apiVersion: v1
kind: Service
metadata:
  name: app-client
  labels:
    run: app-client
spec:
  type: NodePort
  selector:
    name: app-client
  ports:
  - protocol: TCP
    port: 4200
    nodePort: 31000
    name: http