---
apiVersion: v1
kind: Pod
metadata:
  name: app-client
  labels:
    name: app-client
spec:
  replicas: 1
  restartPolicy: "Always"
  containers:
  - name: app-client
    image: registry.eu-gb.bluemix.net/koopman/digitalcmr_client
    imagePullPolicy: Always
    imagePullSecrets:
    - name: bluemix-uk-registry
    command: ["sh", "-c", "./node_modules/.bin/ng serve -H 0.0.0.0 -e prod --disable-host-check"]
