---
kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
    name: app-server
spec:
    replicas: 1
    serviceName: app-server
    template:
        metadata:
            labels:
                tier: app-server
        spec:
            terminationGracePeriodSeconds: 10
            containers:
              - name: app-server
                image: registry.eu-gb.bluemix.net/koopman/digitalcmr_server
                imagePullPolicy: Always
                imagePullSecrets:
                - name: bluemix-uk-registry
                command: ["sh", "-c", "npm start"]
                env:
                - name: NODE_ENV
                  value: development
                - name: INIT
                  value: "true"
                - name: HOST
                  value: "0.0.0.0"
                - name: PORT
                  value: "8080"
                  volumeMounts:
                    - name: credentials-pv
                      mountPath: /home/composer/.composer-credentials
    volumeClaimTemplates:
        - metadata:
            name: credentials-pv
          spec:
              accessModes:
                  - ReadWriteOnce
              resources:
                  requests:
                      storage: 100M
              selector:
                matchLabels:
                  vol: credentials-pv
              storageClassName: ""