---
apiVersion: v1
kind: Pod
metadata:
  name: composer-identity-import-kpm-all
spec:
  restartPolicy: "Never"
  containers:
  - name: composer-identity-import-kpm-all
    image: hyperledger/composer-cli:0.13.2
    imagePullPolicy: Always
    command: ["sh", "-c", "sleep 1 && while [ ! -d /fabric-config/Admin@kpm-all ]; do echo Waiting for identity data; sleep 1; done; composer identity import -p kpm-all -u admin -c /fabric-config/Admin@kpm-all/msp/signcerts/Admin@kpm-all-cert.pem -k /fabric-config/Admin@kpm-all/msp/keystore/`ls /fabric-config/Admin@kpm-all/msp/keystore` && echo 'Done with importing identity'; composer network deploy -a /fabric-config/bna/digital-cmr-network.bna -i admin -s passwd -p kpm-all && echo 'Done with deploying'"]
    env:
    - name: COMPOSER_CONFIG
      value: >
        {
          "defaultConnectionProfile": "kpm-all",
          "connectionProfiles": {
            "kpm-all": {
              "type": "hlfv1",
              "orderers": [
                  {
                      "url": "grpc://orderer-kpm-all:7050"
                  }
              ],
              "ca": {
                  "url": "http://ca-kpm-all:7054",
                  "name": "ca-kpm-all"
              },
              "peers": [
                  {
                      "requestURL": "grpc://peer0-kpm-all:5010",
                      "eventURL": "grpc://peer0-kpm-all:5011"
                  }
              ],
              "keyValStore": "/home/composer/.composer-credentials",
              "channel": "kpmalliancetrialchannel",
              "mspID": "kpm-allMSP",
              "timeout": "300"
            }
          }
        }
    volumeMounts:
    - name: kpm-all-composer-credentials
      mountPath: /home
    - name: kpm-all-composer-identity-fabric-config
      mountPath: /fabric-config
  volumes:
  - name: kpm-all-composer-credentials
    hostPath:
      path: /composer
  - name: kpm-all-composer-identity-fabric-config
    emptyDir: {}
